generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ReglaLlamadasSimultaneas
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          regla_llamadas_simultaneas
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        cantidadLlamadas:
          label: Llamadas
          help: Cantidad de llamadas simult치neas
        importante:
          label: M치xima seguridad
          help: Si la regla es de m치xima seguridad manda un SMS como alerta
      list:
        display: [nombre, importante, cantidadLlamadas]
        title: Llamadas simult치neas
      filter:  ~
      form:    ~
      edit:
        display: [nombre, importante, cantidadLlamadas]
        title: Editar regla
      new:
        display: [nombre, importante, cantidadLlamadas]
        title: Nueva regla
